# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Generate module jars
        run: mvn clean install -DskipTests
      - name: Build & Push Docker data-service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./data-service
          image: ivandvurechenskiy/data-service
          tags: latest
          registry: docker.io
          dockerfile: ./data-service/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image Send-Manager
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./send-manager
          image: ivandvurechenskiy/new-send-manager
          tags: latest
          registry: docker.io
          dockerfile: ./send-manager/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image sender-service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./sender-service
          image: ivandvurechenskiy/new-sender-service
          tags: latest
          registry: docker.io
          dockerfile: ./sender-service/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}

